#############################################################################
# Makefile for building: osornod
# Generated by qmake (2.01a) (Qt 4.8.6) on: Fri Jun 8 17:20:43 2018
# Project:  osornod.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile osornod.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/local/pvb/pvserver -I/usr/local/pvb/rllib/lib
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   /usr/lib/libpvsmt.so -lpthread /usr/lib/librllib.so 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mask7.cpp \
		mask6.cpp \
		mask5.cpp \
		mask4.cpp \
		mask3.cpp \
		mask2.cpp \
		mask1.cpp \
		simpledate.cpp \
		osornoconf.cpp \
		pvapp.cpp \
		dispatcher.cpp \
		logger.cpp \
		plcserver.cpp 
OBJECTS       = main.o \
		mask7.o \
		mask6.o \
		mask5.o \
		mask4.o \
		mask3.o \
		mask2.o \
		mask1.o \
		simpledate.o \
		osornoconf.o \
		pvapp.o \
		dispatcher.o \
		logger.o \
		plcserver.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		osornod.pro
QMAKE_TARGET  = osornod
DESTDIR       = 
TARGET        = osornod

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: osornod.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile osornod.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile osornod.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/osornod1.0.0 || $(MKDIR) .tmp/osornod1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/osornod1.0.0/ && (cd `dirname .tmp/osornod1.0.0` && $(TAR) osornod1.0.0.tar osornod1.0.0 && $(COMPRESS) osornod1.0.0.tar) && $(MOVE) `dirname .tmp/osornod1.0.0`/osornod1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/osornod1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp pvapp.h \
		shamemchl.h \
		osornoconf.h \
		oscadaserv.h \
		logger.h \
		simpledate.h \
		dispatcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mask7.o: mask7.cpp pvapp.h \
		mask7_slots.h \
		shamemchl.h \
		oscadaserv.h \
		osornoconf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask7.o mask7.cpp

mask6.o: mask6.cpp pvapp.h \
		mask6_slots.h \
		shamemchl.h \
		osornoconf.h \
		dispatcher.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask6.o mask6.cpp

mask5.o: mask5.cpp pvapp.h \
		mask5_slots.h \
		logger.h \
		osornoconf.h \
		dispatcher.h \
		shamemchl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask5.o mask5.cpp

mask4.o: mask4.cpp pvapp.h \
		mask4_slots.h \
		shamemchl.h \
		logger.h \
		dispatcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask4.o mask4.cpp

mask3.o: mask3.cpp pvapp.h \
		mask3_slots.h \
		osornoconf.h \
		shamemchl.h \
		dispatcher.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask3.o mask3.cpp

mask2.o: mask2.cpp pvapp.h \
		mask2_slots.h \
		shamemchl.h \
		dispatcher.h \
		logger.h \
		osornoconf.h \
		osaut.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask2.o mask2.cpp

mask1.o: mask1.cpp pvapp.h \
		mask1_slots.h \
		shamemchl.h \
		oscadaserv.h \
		osornoconf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mask1.o mask1.cpp

simpledate.o: simpledate.cpp simpledate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simpledate.o simpledate.cpp

osornoconf.o: osornoconf.cpp pvapp.h \
		shamemchl.h \
		osornoconf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o osornoconf.o osornoconf.cpp

pvapp.o: pvapp.cpp pvapp.h \
		osaut.h \
		logger.h \
		shamemchl.h \
		osornoconf.h \
		dispatcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pvapp.o pvapp.cpp

dispatcher.o: dispatcher.cpp pvapp.h \
		osaut.h \
		shamemchl.h \
		osornoconf.h \
		bio_errors.h \
		logger.h \
		dispatcher.h \
		simpledate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dispatcher.o dispatcher.cpp

logger.o: logger.cpp logger.h \
		shamemchl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

plcserver.o: plcserver.cpp osaut.h \
		shamemchl.h \
		oscadaserv.h \
		osornoconf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plcserver.o plcserver.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

