/*****************************************************************************
 * mask7.cpp
 *                        --------------------------------------------
 *  begin                 : Tue Jun 5 11:07:41 2018
 *  template generated by : pvdevelop (C) Lehrig Software Engineering
 *  email                 : lehrig@t-online.de 
 *                        --------------------------------------------
 * This file is part of OSAUT and OSORNOD projects. OSAUT is a free definition,
 * ehich may be used under the Creative Commons Share-alike license with the
 * additional condition of notifying the original author(s) of deviations and
 * expansion of the work.OSORNOD is intended to be released in the near future
 * as free software that you then can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, version 3. However,up to that point, OSORNOD software
 * and any or all of its components are proprietary and may not be modified or
 * distributed without express approval of Osorno Enterprises Inc.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GNU General Public License can be obtained from the Free 
 * Software Foundation, Inc., 51  Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301 USA.
 *
 * Copyright Osorno Enterprises Inc., 2018
 *
 * OSAUT and OSORNOD project
 * (c) Osorno Enterprises Inc., 2018: http://www.osorno.ca/
 * 
 ****************************************************************************/
#include "pvapp.h"

// _begin_of_generated_area_ (do not edit -> use ui2pvc) -------------------

// our mask contains the following objects
enum {
  ID_MAIN_WIDGET = 0,
  frmBg,
  imgHeader,
  lblHeader,
  frmTopSeparator,
  frmBottomSeparator,
  lblLink,
  btnMainMenu,
  imgBlockFg,
  lblUperStatus,
  imgCIP_schematic,
  imgCIP_Solenoid_7,
  imgCIP_Solenoid_8,
  imgCIP_pump,
  imgCIP_lvlsw_low,
  imgCIP_lvlsw_high,
  imgCIP_lvlsw_emer,
  ID_END_OF_WIDGETS
};

// our mask contains the following widget names
  static const char *widgetName[] = {
  "ID_MAIN_WIDGET",
  "frmBg",
  "imgHeader",
  "lblHeader",
  "frmTopSeparator",
  "frmBottomSeparator",
  "lblLink",
  "btnMainMenu",
  "imgBlockFg",
  "lblUperStatus",
  "imgCIP_schematic",
  "imgCIP_Solenoid_7",
  "imgCIP_Solenoid_8",
  "imgCIP_pump",
  "imgCIP_lvlsw_low",
  "imgCIP_lvlsw_high",
  "imgCIP_lvlsw_emer",
  "ID_END_OF_WIDGETS",
  ""};

  static const char *toolTip[] = {
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ""};

  static const char *whatsThis[] = {
  "",
  "",
  "images/osorno_logo.png",
  "",
  "",
  "",
  "",
  "",
  "images/block_fg.png",
  "",
  "images/misc/cip_schematic.png",
  "images/icons25x25/gray25x25.png",
  "images/icons25x25/gray25x25.png",
  "images/icons25x25/gray25x25.png",
  "images/icons30x20/lvlsw_inactive.png",
  "images/icons30x20/lvlsw_inactive.png",
  "images/icons30x20/lvlsw_inactive.png",
  ""};

  static const int widgetType[ID_END_OF_WIDGETS+1] = {
  0,
  TQFrame,
  TQImage,
  TQLabel,
  TQFrame,
  TQFrame,
  TQLabel,
  TQPushButton,
  TQImage,
  TQLabel,
  TQImage,
  TQImage,
  TQImage,
  TQImage,
  TQImage,
  TQImage,
  TQImage,
  -1 };

static int generated_defineMask(PARAM *p)
{
  int w,h,depth;

  if(p == NULL) return 1;
  if(widgetName[0] == NULL) return 1; // suppress unused warning
  w = h = depth = strcmp(toolTip[0],whatsThis[0]);
  if(widgetType[0] == -1) return 1;
  if(w==h) depth=0; // fool the compiler
  pvStartDefinition(p,ID_END_OF_WIDGETS);

  pvQFrame(p,frmBg,0,NoFrame,Plain,0,1);
  pvSetGeometry(p,frmBg,1,1,800,600);
  pvSetPaletteBackgroundColor(p,frmBg,200,200,180);
  pvSetFont(p,frmBg,"Sans",10,0,0,0,0);

  pvDownloadFile(p,"images/osorno_logo.png");
  pvQImage(p,imgHeader,frmBg,"images/osorno_logo.png",&w,&h,&depth);
  pvSetGeometry(p,imgHeader,570,22,192,49);
  pvSetFont(p,imgHeader,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgHeader,pvtr("images/osorno_logo.png"));

  pvQLabel(p,lblHeader,frmBg);
  pvSetGeometry(p,lblHeader,18,15,430,60);
  pvSetText(p,lblHeader,pvtr("Microfiltration System"));
  pvSetPaletteForegroundColor(p,lblHeader,150,150,100);
  pvSetFont(p,lblHeader,"Sans",24,0,0,0,0);

  pvQFrame(p,frmTopSeparator,frmBg,HLine,Sunken,1,1);
  pvSetGeometry(p,frmTopSeparator,1,86,800,2);
  pvSetFont(p,frmTopSeparator,"Sans",10,0,0,0,0);

  pvQFrame(p,frmBottomSeparator,frmBg,HLine,Sunken,1,1);
  pvSetGeometry(p,frmBottomSeparator,1,540,800,2);
  pvSetFont(p,frmBottomSeparator,"Sans",10,0,0,0,0);

  pvQLabel(p,lblLink,frmBg);
  pvSetGeometry(p,lblLink,18,555,300,30);
  pvSetText(p,lblLink,pvtr("www.osorno.ca"));
  pvSetPaletteForegroundColor(p,lblLink,150,150,100);
  pvSetFont(p,lblLink,"Sans",18,0,0,1,0);

  pvQPushButton(p,btnMainMenu,frmBg);
  pvSetGeometry(p,btnMainMenu,620,552,140,35);
  pvSetText(p,btnMainMenu,pvtr("Main Menu"));
  pvSetFont(p,btnMainMenu,"Sans",12,0,0,0,0);

  pvDownloadFile(p,"images/block_fg.png");
  pvQImage(p,imgBlockFg,frmBg,"images/block_fg.png",&w,&h,&depth);
  pvSetGeometry(p,imgBlockFg,799,599,800,600);
  pvSetFont(p,imgBlockFg,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgBlockFg,pvtr("images/block_fg.png"));

  pvQLabel(p,lblUperStatus,frmBg);
  pvSetGeometry(p,lblUperStatus,180,65,540,20);
  pvSetPaletteForegroundColor(p,lblUperStatus,149,54,27);
  pvSetFont(p,lblUperStatus,"Sans",13,0,1,0,0);

  pvDownloadFile(p,"images/misc/cip_schematic.png");
  pvQImage(p,imgCIP_schematic,frmBg,"images/misc/cip_schematic.png",&w,&h,&depth);
  pvSetGeometry(p,imgCIP_schematic,0,0,800,408);
  pvSetFont(p,imgCIP_schematic,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgCIP_schematic,pvtr("images/misc/cip_schematic.png"));

  pvDownloadFile(p,"images/icons25x25/gray25x25.png");
  pvQImage(p,imgCIP_Solenoid_7,imgCIP_schematic,"images/icons25x25/gray25x25.png",&w,&h,&depth);
  pvSetGeometry(p,imgCIP_Solenoid_7,603,138,25,25);
  pvSetFont(p,imgCIP_Solenoid_7,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgCIP_Solenoid_7,pvtr("images/icons25x25/gray25x25.png"));

  pvDownloadFile(p,"images/icons25x25/gray25x25.png");
  pvQImage(p,imgCIP_Solenoid_8,imgCIP_schematic,"images/icons25x25/gray25x25.png",&w,&h,&depth);
  pvSetGeometry(p,imgCIP_Solenoid_8,483,257,25,25);
  pvSetFont(p,imgCIP_Solenoid_8,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgCIP_Solenoid_8,pvtr("images/icons25x25/gray25x25.png"));

  pvDownloadFile(p,"images/icons25x25/gray25x25.png");
  pvQImage(p,imgCIP_pump,imgCIP_schematic,"images/icons25x25/gray25x25.png",&w,&h,&depth);
  pvSetGeometry(p,imgCIP_pump,597,234,25,25);
  pvSetFont(p,imgCIP_pump,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgCIP_pump,pvtr("images/icons25x25/gray25x25.png"));

  pvDownloadFile(p,"images/icons30x20/lvlsw_inactive.png");
  pvQImage(p,imgCIP_lvlsw_low,imgCIP_schematic,"images/icons30x20/lvlsw_inactive.png",&w,&h,&depth);
  pvSetGeometry(p,imgCIP_lvlsw_low,300,240,30,30);
  pvSetFont(p,imgCIP_lvlsw_low,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgCIP_lvlsw_low,pvtr("images/icons30x20/lvlsw_inactive.png"));

  pvDownloadFile(p,"images/icons30x20/lvlsw_inactive.png");
  pvQImage(p,imgCIP_lvlsw_high,imgCIP_schematic,"images/icons30x20/lvlsw_inactive.png",&w,&h,&depth);
  pvSetGeometry(p,imgCIP_lvlsw_high,300,192,30,30);
  pvSetFont(p,imgCIP_lvlsw_high,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgCIP_lvlsw_high,pvtr("images/icons30x20/lvlsw_inactive.png"));

  pvDownloadFile(p,"images/icons30x20/lvlsw_inactive.png");
  pvQImage(p,imgCIP_lvlsw_emer,imgCIP_schematic,"images/icons30x20/lvlsw_inactive.png",&w,&h,&depth);
  pvSetGeometry(p,imgCIP_lvlsw_emer,297,141,99,30);
  pvSetFont(p,imgCIP_lvlsw_emer,"Sans",10,0,0,0,0);
  pvSetWhatsThis(p,imgCIP_lvlsw_emer,pvtr("images/icons30x20/lvlsw_inactive.png"));


  pvEndDefinition(p);
  return 0;
}

// _end_of_generated_area_ (do not edit -> use ui2pvc) ---------------------

#include "mask7_slots.h"

dev_uistate_t DeltaDevices_Mask7[MAX_DEV_NUM]= {
  { DEV_SOL7,       { imgCIP_Solenoid_7,     STAT_DSCN }},
  { DEV_SOL8,       { imgCIP_Solenoid_8,     STAT_DSCN }},
  { DEV_CIP_LVLSW_L,{ imgCIP_lvlsw_low,      STAT_DSCN }},
  { DEV_CIP_LVLSW_H,{ imgCIP_lvlsw_high,     STAT_DSCN }},
  { DEV_CIP_LVLSW_E,{ imgCIP_lvlsw_emer,     STAT_DSCN }},
  { DEV_CIP_PUMP,   { imgCIP_pump,           STAT_DSCN }},
};

//!****************************************************************************
static int defineMask(PARAM *p)
{
  if(p == NULL) return 1;
  generated_defineMask(p);
  // (todo: add your code here)
  /*if (globs != NULL && globs->stop_app){
     pvShow(p, lblMessage);
     pvHide(p, btnMainMenu);
  } else {
     pvHide(p, lblMessage);
     pvShow(p, btnMainMenu);
  }*/
  return 0;
}


//!****************************************************************************
static int showData(PARAM *p, DATA *d)
{
  if (p == NULL || d == NULL) return 1;

  ////observer_timeout_monitoring(p, imgBlockFg, lblUperStatus, &(d->session));
  
  return 0;
}

//!****************************************************************************
static int readData(DATA *d) // from shared memory, database or something else
{
  if(d == NULL) return 1;
  // (todo: add your code here)
  return 0;
}

//!****************************************************************************
int show_mask7(PARAM *p)
{
  DATA d;
  char event[MAX_EVENT_LENGTH];
  char text[MAX_EVENT_LENGTH];
  char str1[MAX_EVENT_LENGTH];
  int  i,w,h,val,x,y,button,ret;
  float xval, yval;

  defineMask(p);
  //rlSetDebugPrintf(1);
  if((ret=slotInit(p,&d)) != 0) return ret;
  readData(&d); // from shared memory, database or something else
  showData(p,&d);
  pvClearMessageQueue(p);
  
  while(1)
  {
    pvPollEvent(p,event);
    switch(pvParseEvent(event, &i, text))
    {
      case NULL_EVENT:
        readData(&d); // from shared memory, database or something else
        showData(p,&d);
        if((ret=slotNullEvent(p,&d)) != 0) return ret;
        break;
      case BUTTON_EVENT:
        if(trace) printf("BUTTON_EVENT id=%d\n",i);
        if((ret=slotButtonEvent(p,i,&d)) != 0) return ret;
        break;
      case BUTTON_PRESSED_EVENT:
        if(trace) printf("BUTTON_PRESSED_EVENT id=%d\n",i);
        if((ret=slotButtonPressedEvent(p,i,&d)) != 0) return ret;
        break;
      case BUTTON_RELEASED_EVENT:
        if(trace) printf("BUTTON_RELEASED_EVENT id=%d\n",i);
        if((ret=slotButtonReleasedEvent(p,i,&d)) != 0) return ret;
        break;
      case TEXT_EVENT:
        if(trace) printf("TEXT_EVENT id=%d %s\n",i,text);
        if((ret=slotTextEvent(p,i,&d,text)) != 0) return ret;
        break;
      case SLIDER_EVENT:
        sscanf(text,"(%d)",&val);
        if(trace) printf("SLIDER_EVENT val=%d\n",val);
        if((ret=slotSliderEvent(p,i,&d,val)) != 0) return ret;
        break;
      case CHECKBOX_EVENT:
        if(trace) printf("CHECKBOX_EVENT id=%d %s\n",i,text);
        if((ret=slotCheckboxEvent(p,i,&d,text)) != 0) return ret;
        break;
      case RADIOBUTTON_EVENT:
        if(trace) printf("RADIOBUTTON_EVENT id=%d %s\n",i,text);
        if((ret=slotRadioButtonEvent(p,i,&d,text)) != 0) return ret;
        break;
      case GL_INITIALIZE_EVENT:
        if(trace) printf("you have to call initializeGL()\n");
        if((ret=slotGlInitializeEvent(p,i,&d)) != 0) return ret;
        break;
      case GL_PAINT_EVENT:
        if(trace) printf("you have to call paintGL()\n");
        if((ret=slotGlPaintEvent(p,i,&d)) != 0) return ret;
        break;
      case GL_RESIZE_EVENT:
        sscanf(text,"(%d,%d)",&w,&h);
        if(trace) printf("you have to call resizeGL(w,h)\n");
        if((ret=slotGlResizeEvent(p,i,&d,w,h)) != 0) return ret;
        break;
      case GL_IDLE_EVENT:
        if((ret=slotGlIdleEvent(p,i,&d)) != 0) return ret;
        break;
      case TAB_EVENT:
        sscanf(text,"(%d)",&val);
        if(trace) printf("TAB_EVENT(%d,page=%d)\n",i,val);
        if((ret=slotTabEvent(p,i,&d,val)) != 0) return ret;
        break;
      case TABLE_TEXT_EVENT:
        sscanf(text,"(%d,%d,",&x,&y);
        pvGetText(text,str1);
        if(trace) printf("TABLE_TEXT_EVENT(%d,%d,\"%s\")\n",x,y,str1);
        if((ret=slotTableTextEvent(p,i,&d,x,y,str1)) != 0) return ret;
        break;
      case TABLE_CLICKED_EVENT:
        sscanf(text,"(%d,%d,%d)",&x,&y,&button);
        if(trace) printf("TABLE_CLICKED_EVENT(%d,%d,button=%d)\n",x,y,button);
        if((ret=slotTableClickedEvent(p,i,&d,x,y,button)) != 0) return ret;
        break;
      case SELECTION_EVENT:
        sscanf(text,"(%d,",&val);
        pvGetText(text,str1);
        if(trace) printf("SELECTION_EVENT(column=%d,\"%s\")\n",val,str1);
        if((ret=slotSelectionEvent(p,i,&d,val,str1)) != 0) return ret;
        break;
      case CLIPBOARD_EVENT:
        sscanf(text,"(%d",&val);
        if(trace) printf("CLIPBOARD_EVENT(id=%d)\n",val);
        if(trace) printf("clipboard = \n%s\n",p->clipboard);
        if((ret=slotClipboardEvent(p,i,&d,val)) != 0) return ret;
        break;
      case RIGHT_MOUSE_EVENT:
        if(trace) printf("RIGHT_MOUSE_EVENT id=%d text=%s\n",i,text);
        if((ret=slotRightMouseEvent(p,i,&d,text)) != 0) return ret;
        break;
      case KEYBOARD_EVENT:
        sscanf(text,"(%d",&val);
        if(trace) printf("KEYBOARD_EVENT modifier=%d key=%d\n",i,val);
        if((ret=slotKeyboardEvent(p,i,&d,val,i)) != 0) return ret;
        break;
      case PLOT_MOUSE_MOVED_EVENT:
        sscanf(text,"(%f,%f)",&xval,&yval);
        if(trace) printf("PLOT_MOUSE_MOVE %f %f\n",xval,yval);
        if((ret=slotMouseMovedEvent(p,i,&d,xval,yval)) != 0) return ret;
        break;
      case PLOT_MOUSE_PRESSED_EVENT:
        sscanf(text,"(%f,%f)",&xval,&yval);
        if(trace) printf("PLOT_MOUSE_PRESSED %f %f\n",xval,yval);
        if((ret=slotMousePressedEvent(p,i,&d,xval,yval)) != 0) return ret;
        break;
      case PLOT_MOUSE_RELEASED_EVENT:
        sscanf(text,"(%f,%f)",&xval,&yval);
        if(trace) printf("PLOT_MOUSE_RELEASED %f %f\n",xval,yval);
        if((ret=slotMouseReleasedEvent(p,i,&d,xval,yval)) != 0) return ret;
        break;
      case MOUSE_OVER_EVENT:
        sscanf(text,"%d",&val);
        if(trace) printf("MOUSE_OVER_EVENT %d\n",val);
        if((ret=slotMouseOverEvent(p,i,&d,val)) != 0) return ret;
        break;
      case USER_EVENT:
        if(trace) printf("USER_EVENT id=%d %s\n",i,text);
        if((ret=slotUserEvent(p,i,&d,text)) != 0) return ret;
        break;
      default:
        if(trace) printf("UNKNOWN_EVENT id=%d %s\n",i,text);
        break;
    }
  }
}
